### ISSUE TITLE
json = false for a bunch of methods

### ISSUE THREAD

**Issue by matthewjumpsoffbuildings** [Yaaqoub/node-harvest-v2#24]
Why is something like `timeEntries.create()` configured with `this.json = false`? It means the json response object the Harvest API sends back is not automatically parsed as JSON, instead its returning a string? This makes no sense. Dont all the Harvest API endpoints return JSON if anything?

**Comment by Yaaqoub** [comment]
Hello @matthewjumpsoffbuildings 

I am sorry for my late response .

GET requests:  Harvest returns JSON string so we used "request-promise" parameter to parse JSON
`
json: true
`

POST / PATCH / DELETE we used
`
json: false
`
Because the data we send is a stringify JSON.

For example:

The results using `this.options.json = true;`:
![image](https://user-images.githubusercontent.com/11662053/65948804-3979d580-e43b-11e9-8bcf-34153f3d85c7.png)

The results using `this.options.json = false;` or removing it completely:
![image](https://user-images.githubusercontent.com/11662053/65948945-852c7f00-e43b-11e9-821d-b895436d883a.png)
